# Generated by Django 5.2.8 on 2025-12-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('query_raw', models.TextField()),
                ('query_clean', models.TextField()),
                ('best_store', models.CharField(blank=True, max_length=255, null=True)),
                ('best_title', models.TextField(blank=True, null=True)),
                ('best_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('best_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
