# Generated by Django 6.0 on 2025-12-13 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('store', models.CharField(blank=True, default='', max_length=128)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, default='BRL', max_length=8)),
                ('target_url', models.URLField(max_length=2048)),
                ('clicks', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OfferClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('referer', models.CharField(blank=True, default='', max_length=1024)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='prices.offerlink')),
            ],
        ),
    ]
