# prices/mock_data/makeup_products.py

MOCK_MAKEUP_PRODUCTS = [
    # FACE
    {
        "store": "Loja Mock Make 1",
        "source": "mock_makeup",
        "id": "MM1-001",
        "category": "face",
        "title": "Base líquida matte para pele oleosa - Marca X",
        "price": 59.90,
        "currency": "BRL",
        "url": "https://exemplo.com/produto/base-matte-oleosa",
        "thumbnail": "https://exemplo.com/img/base-matte.jpg",
    },
    {
        "store": "Loja Mock Make 2",
        "source": "mock_makeup",
        "id": "MM1-002",
        "category": "face",
        "title": "Corretivo alta cobertura para olheiras - Marca Y",
        "price": 39.90,
        "currency": "BRL",
        "url": "https://exemplo.com/produto/corretivo-alta-cobertura",
        "thumbnail": "https://exemplo.com/img/corretivo.jpg",
    },
    {
        "store": "Loja Mock Make 3",
        "source": "mock_makeup",
        "id": "MM1-003",
        "category": "face",
        "title": "Pó compacto translúcido anti-brilho - Marca Z",
        "price": 44.90,
        "currency": "BRL",
        "url": "https://exemplo.com/produto/po-compacto-translucido",
        "thumbnail": "https://exemplo.com/img/po-compacto.jpg",
    },

    # EYES
    {
        "store": "Loja Mock Make 1",
        "source": "mock_makeup",
        "id": "MM2-001",
        "category": "eyes",
        "title": "Máscara de cílios à prova d’água volume máximo",
        "price": 49.90,
        "currency": "BRL",
        "url": "https://exemplo.com/produto/mascara-cilios",
        "thumbnail": "https://exemplo.com/img/mascara-cilios.jpg",
    },
    {
        "store": "Loja Mock Make 2",
        "source": "mock_makeup",
        "id": "MM2-002",
        "category": "eyes",
        "title": "Delineador líquido preto ponta fina",
        "price": 29.90,
        "currency": "BRL",
        "url": "https://exemplo.com/produto/delineador-liquido-preto",
        "thumbnail": "https://exemplo.com/img/delineador.jpg",
    },
    {
        "store": "Loja Mock Make 3",
        "source": "mock_makeup",
        "id": "MM2-003",
        "category": "eyes",
        "title": "Paleta de sombras neutras 12 cores",
        "price": 79.90,
        "currency": "BRL",
        "url": "https://exemplo.com/produto/paleta-sombras-neutras",
        "thumbnail": "https://exemplo.com/img/paleta-neutra.jpg",
    },

    # LIPS
    {
        "store": "Loja Mock Make 1",
        "source": "mock_makeup",
        "id": "MM3-001",
        "category": "lips",
        "title": "Batom vermelho matte longa duração - Marca Y",
        "price": 34.90,
        "currency": "BRL",
        "url": "https://exemplo.com/produto/batom-vermelho-matte",
        "thumbnail": "https://exemplo.com/img/batom-vermelho.jpg",
    },
    {
        "store": "Loja Mock Make 2",
        "source": "mock_makeup",
        "id": "MM3-002",
        "category": "lips",
        "title": "Gloss labial incolor efeito espelhado",
        "price": 27.50,
        "currency": "BRL",
        "url": "https://exemplo.com/produto/gloss-incolor",
        "thumbnail": "https://exemplo.com/img/gloss.jpg",
    },

    # SKINCARE
    {
        "store": "Loja Mock Skincare",
        "source": "mock_makeup",
        "id": "MM4-001",
        "category": "skincare",
        "title": "Hidratante facial para pele oleosa oil free",
        "price": 64.90,
        "currency": "BRL",
        "url": "https://exemplo.com/produto/hidratante-facial-oleosa",
        "thumbnail": "https://exemplo.com/img/hidratante.jpg",
    },
    {
        "store": "Loja Mock Skincare",
        "source": "mock_makeup",
        "id": "MM4-002",
        "category": "skincare",
        "title": "Protetor solar facial FPS 50 textura leve",
        "price": 79.90,
        "currency": "BRL",
        "url": "https://exemplo.com/produto/protetor-solar-fps50",
        "thumbnail": "https://exemplo.com/img/protetor-solar.jpg",
    },
]
